server:
  port: 8080
 
spring:
  datasource:
    username: root
    password: 
    url: jdbc:mysql://localhost:3306/spider?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.clz.spider.entity
 
#showSql
logging:
  level:
    com:
      clz:
        mapper : debug